# Generated by Django 5.2.8 on 2025-11-26 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('github_username', models.CharField(blank=True, max_length=100, null=True)),
                ('github_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('github_access_token', models.TextField(blank=True, null=True)),
                ('github_bio', models.TextField(blank=True, null=True)),
                ('github_company', models.CharField(blank=True, max_length=200, null=True)),
                ('github_location', models.CharField(blank=True, max_length=200, null=True)),
                ('github_followers', models.IntegerField(default=0)),
                ('github_following', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GithubFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend_github_id', models.CharField(max_length=100)),
                ('friend_username', models.CharField(max_length=100)),
                ('friend_profile_image', models.URLField(blank=True, null=True)),
                ('friend_bio', models.TextField(blank=True, null=True)),
                ('relationship_type', models.CharField(choices=[('follower', 'Follower'), ('following', 'Following'), ('mutual', 'Mutual')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='github_connections', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_friends', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'friend_github_id')},
            },
        ),
    ]
