# Generated by Django 5.2.8 on 2025-12-01 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_remove_message_is_edited_remove_message_message_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='AI 세션의 고유 식별자 (UUID)', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='세션 활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='세션 생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='세션 마지막 업데이트 시간')),
                ('base_room', models.ForeignKey(help_text='AI 세션이 연결된 기본 채팅방', on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='chat.chatroom')),
            ],
            options={
                'verbose_name': 'AI Chat Session',
                'verbose_name_plural': 'AI Chat Sessions',
                'db_table': 'llm_ai_chat_session',
                'ordering': ['-created_at'],
            },
        ),
    ]
