# Generated by Django 5.2.8 on 2025-11-27 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_alter_chatroom_options_rename_room_message_chatroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_sessions', to='chat.chatroom')),
            ],
        ),
    ]
