# Generated by Django 5.2.8 on 2025-12-01 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llm', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='메시지 내용')),
                ('is_ai_message', models.BooleanField(default=False, help_text='AI가 생성한 메시지인지 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='메시지 생성 시간')),
                ('sender', models.ForeignKey(help_text='메시지 발신자 (사용자 또는 AI)', on_delete=django.db.models.deletion.CASCADE, to='login.userprofile')),
                ('session', models.ForeignKey(help_text='AI 세션별 메시지 그룹화', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='llm.aichatsession')),
            ],
            options={
                'verbose_name': 'AI Chat Message',
                'verbose_name_plural': 'AI Chat Messages',
                'db_table': 'llm_ai_chat_message',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='llm_ai_chat_session_bba4be_idx'), models.Index(fields=['sender', 'created_at'], name='llm_ai_chat_sender__955b75_idx')],
            },
        ),
    ]
