# Generated by Django 5.2.8 on 2025-12-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_is_edited_remove_message_message_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_ai_chat',
            field=models.BooleanField(default=False, help_text='AI 채팅방 메시지인지 여부'),
        ),
    ]
